[SDK] Update iexec-sdk version
iExecBlockchainComputing/web3mail-sdk pull request #131
Opened 2024-06-20 14:13 UTC by Le-Caignec

2024-06-24 07:52 UTC, PierreJeanjacquot requested changes
- see comments (NB: error message to be discussed with the team)
- add some tests (use a fake URL to trigger a DNS error on a service)

2024-06-24 07:52 UTC, PierreJeanjacquot commented on src/utils/errors.ts
> -    this.originalError = originalError;
we should keep `originalError` and deprecate its usage, removing it is a breaking change

2024-06-24 07:52 UTC, PierreJeanjacquot commented on src/utils/errors.ts
> +      'A service in the iExec protocol appears to be unavailable. This issue is not caused by your actions, please contact iexec technical support:',
not sure about the error message:
- it might be too scary ("retry later" can be an option)
- the affected service is not mentioned

2024-06-24 07:52 UTC, PierreJeanjacquot commented on src/utils/errors.ts
> +  return false;
do we need to return a boolean?

2024-06-24 07:52 UTC, PierreJeanjacquot commented on CHANGELOG.md
> +
no error classes added

```suggestion
```

2024-06-24 09:21 UTC, Le-Caignec commented on src/utils/errors.ts
> -    this.originalError = originalError;
We discussed this with Cédric and decided to remove that as the workflow type is not exported. So nobody could use it. We will note this in the changelog.

2024-06-24 09:22 UTC, Le-Caignec commented on src/utils/errors.ts
> -    this.originalError = originalError;
Commit: 8a19a96a51e3f914ff3c043e8b05648fc21b8692

2024-06-24 09:30 UTC, Le-Caignec commented on src/utils/errors.ts
> +      'A service in the iExec protocol appears to be unavailable. This issue is not caused by your actions, please contact iexec technical support:',
done => Commit: bf932094b2b49752f9e0c7116f60137025c1dc3e

2024-06-24 09:33 UTC, Le-Caignec commented on src/utils/errors.ts
> -    this.originalError = originalError;
export workflow error => Commit: 6677c3a6fc3b6f6b29b2c3c2282752aa337dd909

2024-06-24 14:44 UTC, cedric25 requested changes
I will also propose an additional PR

2024-06-25 06:43 UTC, Le-Caignec commented on CHANGELOG.md
> +Sure, here is the updated changelog with the added breaking change:
done

2024-06-25 06:43 UTC, Le-Caignec commented on src/utils/errors.ts
> +      "A service in the iExec protocol appears to be unavailable. You can retry later or contact iExec's technical support for help.",
added

2024-06-25 06:43 UTC, Le-Caignec commented on src/web3mail/sendEmail.ts
> +        `Failed to fetch my contacts: ${error.message}`,
done

2024-06-25 06:50 UTC, Le-Caignec commented on CHANGELOG.md
> +
i think yes, but i'm ok to make a `1.0.0` as we are always in `0.6.1`!

2024-06-25 08:37 UTC, PierreJeanjacquot commented on src/utils/subgraphQuery.ts
> +      message: 'Failed to fetch subgraph:',
```suggestion
      message: 'Failed to fetch subgraph',
```

2024-06-25 08:37 UTC, PierreJeanjacquot commented on src/utils/subgraphQuery.ts
> +      message: 'Failed to fetch subgraph:',
```suggestion
      message: 'Failed to fetch subgraph',
```

2024-06-25 08:41 UTC, PierreJeanjacquot commented on CHANGELOG.md
> +- Removed `originalError` from `WorkflowError`
```suggestion
- [BREAKING] Removed `originalError` from `WorkflowError`
```

2024-06-25 08:46 UTC, PierreJeanjacquot commented on tsconfig.json
> +    "lib": ["ES2023"],
this tells TS the runtime supports ES2023, which can change the transpilation result (some ES2022 features can be omitted), IMO remove it and let `target` be the only source of truth

```suggestion
```

2024-06-25 08:46 UTC, PierreJeanjacquot commented on src/web3mail/sendEmail.ts
> +      message: 'Failed to sendEmail:',
```suggestion
      message: 'Failed to sendEmail',
```

2024-06-25 08:47 UTC, PierreJeanjacquot commented on src/web3mail/fetchUserContacts.ts
> +      message: 'Failed to fetch user contacts:',
```suggestion
      message: 'Failed to fetch user contacts',
```

2024-06-25 08:49 UTC, PierreJeanjacquot commented on src/web3mail/IExecWeb3mail.ts
> +    ethProvider?: Eip1193Provider | EnhancedWallet | string,
I would not expose `EnhancedWallet` which is supposed to be low level iexec SDK here
```suggestion
    ethProvider?: Eip1193Provider | Web3SignerProvider | string,
```

2024-06-25 08:57 UTC, PierreJeanjacquot commented on CHANGELOG.md
> +- [BREAKING] Ship ES2022 JavaScript instead of es2015 (aka es6) in order to support `cause` optional field in `Error`:
NB: error cause cannot be polyfilled (https://compat-table.github.io/compat-table/es2016plus/)

2024-06-25 09:36 UTC, Le-Caignec commented on src/utils/errors.ts
> +  return false;
done => removed

2024-06-25 09:38 UTC, Le-Caignec commented on CHANGELOG.md
> +- [BREAKING] Ship ES2022 JavaScript instead of es2015 (aka es6) in order to support `cause` optional field in `Error`:
so must stay in ES2022 ? If i well understand ?

2024-06-25 10:08 UTC, Le-Caignec commented on CHANGELOG.md
> +
A major will be made after discussion ✅

2024-06-26 10:46 UTC, PierreJeanjacquot commented on tests/e2e/fetchUserContacts.test.ts
> +        dataProtectorSubgraph: 'https://test',
IMO this should be flagged as a protocol error (the builder cannot do anything)

2024-06-26 10:46 UTC, PierreJeanjacquot approved these changes

2024-06-26 10:57 UTC, Le-Caignec commented on tests/e2e/fetchUserContacts.test.ts
> +        dataProtectorSubgraph: 'https://test',
TODO in an other PR

2024-06-26 10:58 UTC, merged