Feature/privacypass feature
iExecBlockchainComputing/web3mail-sdk pull request #63
Opened 2023-07-06 12:59 UTC by Le-Caignec

2023-07-07 07:54 UTC, PierreJeanjacquot requested changes
see comments

2023-07-07 08:00 UTC, Le-Caignec commented on package-lock.json
Commit: 65bf307e84da2c0dc008880598d0c7526897537f

2023-07-07 08:02 UTC, Le-Caignec commented on src/web3mail/types.ts
> +  address: Address;
Commit: dc8c1ab51595001e3de8e4cce2c917db81148d6b

2023-07-10 05:43 UTC, PierreJeanjacquot approved these changes
👍

2023-09-22 14:44 UTC, closed without merging