Dapp allow developer to specify from Name associated with the sender
iExecBlockchainComputing/web3mail-sdk pull request #71
Opened 2023-08-30 10:06 UTC by luisccastillo

The sender name is set to be optional and passed through the developer secret 3 (options) using the field "senderTag". The senderTag must not be empty(the variable is rather optional, but not empty), and be between 3 and 20 characters long.  The senderTag length may be modified upon request but it's not recommended to let users have long names since email providers may flag us as spam.

2023-08-30 14:18 UTC, PierreJeanjacquot requested changes
Good job!
I think we should use `senderName` for the option name rather than `senderTag` which is easier to understand see also some minor remarks.

2023-08-30 14:18 UTC, PierreJeanjacquot commented on dapp/tests/unit/validateInputs.test.js
> +      senderTag: undefined,
you can just remove it
```suggestion
```

2023-08-30 14:18 UTC, PierreJeanjacquot commented on dapp/tests/unit/emailService.test.js
> +    const senderTag = undefined;
this variable assignment is useless

2023-08-30 14:18 UTC, PierreJeanjacquot commented on dapp/tests/e2e/app.test.js
> +  it('should fail if IEXEC_REQUESTER_SECRET_3 (options) senderTag lenght is less than 3 characters', async () => {
typo

```suggestion
  it('should fail if IEXEC_REQUESTER_SECRET_3 (options) senderTag length is less than 3 characters', async () => {
```

I suggest using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension in VSCode

2023-08-31 15:15 UTC, luisccastillo commented
Changes updated :)

2023-09-01 14:43 UTC, PierreJeanjacquot approved these changes
LGTM :+1:

2023-09-04 15:21 UTC, merged