Customize web3mail constructor parameters
iExecBlockchainComputing/web3mail-sdk pull request #99
Opened 2023-10-24 09:24 UTC by luisccastillo

Modifies the web3mail constructor to take in parameters regarding the environment:
- IPFs node
- IPFS gateway
- whitelist contract address
- email sender dapp address
- workerpool address (done here since secrets are tied to the workerpol env)  
- data protector subgraph URL

the sendEmail method now allows additional parameters 
- dataset max price : set the desired max price to pay for the dataset
- workerpool max price : set the desired max price to pay for the worker
- app max price : set the desired max price to pay for the app
- label: min 3 chars max 10, used to identify the email campaign via iexec_args

2023-10-25 06:31 UTC, PierreJeanjacquot requested changes

2023-10-25 06:31 UTC, PierreJeanjacquot commented on src/web3mail/IExecWeb3mail.ts
> +  private workerpoolAddressOrEns: AddressOrENS;
`workerpoolAddressOrEns` should not be at the constructor level, only for `sendEmail` method

2023-10-25 06:31 UTC, PierreJeanjacquot commented on src/web3mail/types.ts
> +  ipfsGateway?: string;
these 3 (dappAddressOrENS, ipfsNode, ipfsGateway) should not be part of the `SendEmailParams`, they are injected by the `IExecWeb3mail` instance when invoking the `sendEmail` method

you can split into specific types that will not be exposed externally (see IExecConsumer type)

```ts
export type DappAddressConsumer = {
    dappAddressOrENS: AddressOrENS;
};

export type IpfsNodeConfigConsumer = {
     ipfsNode: string;
};

export type IpfsGatewayConfigConsumer = {
    ipfsGateway: string;
};
```

2023-10-25 06:31 UTC, PierreJeanjacquot commented on src/web3mail/types.ts
> +  dappWhitelistAddress?: AddressOrENS;
these (dappAddressOrENS, dappWhitelistAddress) should not be part of the `FetchContactsParams`, they are injected by the `IExecWeb3mail` instance when invoking the `fetchMyContacts` method.

you can split into specific types that will not be exposed externally (see IExecConsumer type)

2023-10-25 06:31 UTC, PierreJeanjacquot commented on src/web3mail/types.ts
> +  workerpoolAddressOrEns?: AddressOrENS;
remove from the constructor part

```suggestion
```

2023-10-27 08:10 UTC, PierreJeanjacquot approved these changes
LGTM

2023-10-30 11:08 UTC, cedric25 commented
Waiting for: https://github.com/iExecBlockchainComputing/web3mail-sdk/pull/102

2023-10-30 16:02 UTC, merged